# Generated by Django 3.2.18 on 2023-04-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20230423_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_date',
            new_name='created_on',
        ),
    ]
