# Generated by Django 3.2.18 on 2023-04-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
