# Generated by Django 3.2.18 on 2023-04-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='expert',
            new_name='excerpt',
        ),
    ]
