# Generated by Django 3.2.18 on 2023-05-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_expert_blogpost_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_description',
            field=models.CharField(default='An image related to this specific blogpost', max_length=80),
        ),
    ]
