# Generated by Django 3.2.18 on 2023-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_category',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Starters'), (2, 'Mains'), (3, 'Desserts'), (4, 'Bites')], default=0),
        ),
    ]
