# Generated by Django 3.2.18 on 2023-04-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_drinkitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitesItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('item_description', models.CharField(max_length=250, unique=True)),
                ('item_price', models.FloatField()),
                ('item_category', models.IntegerField(choices=[(0, 'New'), (1, 'Assorted'), (2, 'Vegetarian')], default=0)),
                ('item_available', models.BooleanField(default=False)),
            ],
        ),
    ]
